### ISSUE TITLE
ウィジェットでの曜日振替の不具合

### ISSUE THREAD

**Issue by AsagaKosho** [twin-te/twinte-android#10]
2021/01/13（水）は月曜日日課であり、その旨がウィジェットにも表示されているが、水曜日の授業が表示されている。
![Screenshot_20210112-060255.png](https://user-images.githubusercontent.com/17997951/104237851-04f92400-549c-11eb-8b19-d47c1254df5a.png)![Screenshot_20210112-060300.png](https://user-images.githubusercontent.com/17997951/104237871-0aef0500-549c-11eb-9a6a-ab1714a8b19b.png)

**Comment by SIY1121** [comment]
ご報告ありがとうございます
サーバー側の問題であることが発覚したため修正します

**Comment by SIY1121** [comment]
修正が完了しました。
ご確認よろしくお願いします。

**Comment by AsagaKosho** [comment]
@SIY1121 
確認したしました。修正ありがとうございます！
