### ISSUE TITLE
CSVファイルから授業を追加できない

### ISSUE THREAD

**Issue by Mimori256** [twin-te/twinte-android#11]
再現手順:
   Twinteの授業を追加するとき、CSVファイルから追加を選択、ファイル選択ダイアログをタップしても反応なし

ログインの有無にかかわらず選択不可、Webアプリ版をブラウザで開いたときは正常に動作しました。Androidバージョン8.1.0です。

**Comment by SIY1121** [comment]
ご報告ありがとうございます。確認しました。
4月中にアップデートで対応します。
