### ISSUE TITLE
Google ログイン時に TWINS からの時間割インポートができない

### ISSUE THREAD

**Issue by private-yusuke** [twin-te/twinte-android#44]
# 概要
Twin:te に Google でログインしたとき、TWINS からのインポートを試行すると https://github.com/twin-te/twins-to-twinte/blob/320c31bc3a08364a5b1fc32c697938734b3a61e8/sp.js#L41 のダイアログが出てきてしまい、インポートができない。

少なくとも https://github.com/twin-te/twinte-android/commit/a61606a7ef7a60a1ba52302b9af10fff89ce274e から、Google ログインを実施した端末で再現できる（現在の stable バージョンの Android Studio ではこれ以前のコミット時点でのビルドができないため試していない。#25 参照）。

Chrome DevTools を用いて、メインの WebView と、TWINS インポート時の WebView を見比べてみると、後者ではインポートのタイミングで `twinte_session` が Cookie として追加されているような挙動をとるが、前者は追加されずにエラーのダイアログが出ているようである。

**Comment by HosokawaR** [comment]
どうやらこの問題の模様
https://github.com/square/okhttp/pull/8022

上記はすでに merge 済みで、おそらくリリースもされているので対応可能かも

**Comment by private-yusuke** [comment]
https://github.com/twin-te/twinte-android/issues/44#issuecomment-2053552703 で参照されている PR の変更は master ブランチに https://github.com/square/okhttp/commit/85286c3f8ca110cf53a70a7a8e30d396757b11f7 で入っていて、このコミットは 5.0.0-alpha.12 から導入されている。

OkHttp の現在の最新バージョンが 5.0.0-alpha.13 で、このバージョンにも先述した差分は入っているためこれを利用するように変更する必要がある。
また、その変更を加えたとしても、以前に WebView が利用する CookieManager に登録された twinte_session クッキーには SameSite 属性が付与されていないため[^1]、一度 WebView が持つクッキーをすべて破棄する必要がある。ユーザには再ログインしてもらう必要があるため、アップデート後に一度だけクッキーを破棄する処理を実行させたい。

[^1]: Twin:te のサーバーから返却される twinte_session クッキーには SameSite 属性が付与されているが、以前までの OkHttp ではその属性をうまく扱えていなかった。また、twinte-android では OkHttp が処理したレスポンスの結果を元に CookieManager にクッキーを追加していたため、この箇所で SameSite 属性の情報が欠落し、WebView では Twin:te にログインしていないような扱いとなっていた。これは SameSite 属性が付いたクッキーを CookieManager に追加することで解決する。
