### ISSUE TITLE
ウィジェットでNullPointerExceptionが発生し、開発者へ自動報告されない

### ISSUE THREAD

**Issue by inucat** [twin-te/twinte-android#57]
Twin:te のウィジェットを設置しておくと、時々添付画像のような例外が表示される。
リロードを実行すると治るが、この例外は単に握りつぶされていて開発者が追跡できない。

![Screenshot_20241021_103706_com huawei android launcher_edit_641587801668765](https://github.com/user-attachments/assets/3d0c9b19-fdaa-4e75-b2f1-4487b2acdb6e)

- Android 10
- Twin:te 2.1.3
- 発生時期: 2024年10月前後より
- 再現方法: 不明
  - 端末を長時間ロックしたのち、アンロックしてウィジェットを表示させると発生する？

## 影響しそうなファイル

- V3LargeWidgetProvider.kt
- app/src/main/java/net/twinte/android/datastore/schedule/SharedPreferencesScheduleDataStore.kt

**Comment by private-yusuke** [comment]
@inucat [detekt](https://detekt.dev/) でコードのフォーマットをしているため、PR を作成するときには `./gradlew detekt` を何度か実行してフォーマットをかけ、エラーが出なくなったことを確認するようにお願いします 🙇‍♂️
